Disable PNG [skip ci]
Due to:
```
fatal error: error in backend: Function __longjmp_vii is using setjmp/longjmp but does not have +exception-handling target feature
```

Investigate this later.